services:
  - type: web
    name: gold-price-api
    env: docker
    plan: free
    autoDeploy: true

    buildCommand: |
      pip install --upgrade pip
      pip install dvc[s3]
      dvc pull

    startCommand: uvicorn src_versioning.api:app --host 0.0.0.0 --port $PORT